Repository ERICA-Club-Hub/Frontend, pull requests merged in 2025-02, with the labels that each got.

#67 API 호출 코드 인스턴스화
  .env
  .gitignore
  src/api/auth/reissue.ts
  src/api/auth/token.ts
  src/api/axios.ts
  src/pages/club-detail/tab/Intro.tsx
  yarn.lock
Labels: ✨ Feature

#66 어드민 동아리 상세페이지 UI 구현
  README.md
  src/assets/common/dropdown_arrow.svg
  src/assets/common/plus-icon.svg
  src/components/Common/Button.tsx
  src/components/Common/Dropdown/Menu.tsx
  src/components/Common/InputField.tsx
  src/components/Common/TextArea.tsx
  src/components/EventSchedule/EventSchedule.tsx
  src/constants/club-detail-register.ts
  src/constants/navigations.ts
  src/pages/admin/auth/register/RegisterClubPage.tsx
  src/pages/admin/club/detail/AdminClubDetailPage.tsx
  src/pages/admin/club/detail/ClubIntro.tsx
  src/pages/admin/club/detail/RecruitNotice.tsx
  src/pages/admin/club/detail/SummaryInfo.tsx
  src/styles/admin-club-detail/style.ts
Labels: ✨ Feature, 🔨 Refactor

#82 70 resources register UI
  src/App.tsx
  src/components/Common/Button.tsx
  src/pages/admin/union/resources/AdminResourcesRegisterPage.tsx
  src/pages/index.ts
Labels: ✨ Feature

#84 동아리 상세 정보 페이지 API 연동
  src/components/Common/Button.tsx
  src/pages/club-detail/ActivityLogModal.tsx
  src/pages/club-detail/ClubDetailPage.tsx
  src/pages/club-detail/TabContents.tsx
  src/pages/club-detail/tab/Intro.tsx
  src/pages/club-detail/tab/Log.tsx
  src/pages/club-detail/tab/Recruit.tsx
  src/utils/getDefaultImg.ts
Labels: ✨ Feature

#83 어드민 로그인 구현
  package.json
  src/App.tsx
  src/api/apiRequest.ts
  src/api/auth/reissue.ts
  src/api/axiosInstance.ts
  src/components/Common/HeaderMenu.tsx
  src/components/Common/InputField.tsx
  src/hooks/useAdminLogin.ts
  src/pages/admin/auth/login/AdminLoginPage.tsx
  src/pages/club-detail/ActivityLogModal.tsx
  src/pages/club-detail/ClubDetailPage.tsx
  src/pages/club-detail/tab/Intro.tsx
  src/pages/club-detail/tab/Log.tsx
  src/pages/club-detail/tab/Recruit.tsx
  src/pages/notice/ServiceNoticePage.tsx
  src/pages/notice/UnionNoticePage.tsx
  src/pages/resources/ResourcesPage.tsx
  src/routes/AuthGuard.tsx
  src/routes/RedirectIfAuthenticated.tsx
  src/routes/Routes.tsx
  src/routes/UnionAdminGuard.tsx
  src/store/authState.ts
  src/store/clubIdState.ts
  src/types/api.types.ts
  src/utils/tokenHandler.ts
  yarn.lock
Labels: ✨ Feature, 🔨 Refactor

#91 모달 공통 컴포넌트 구현
  src/components/Common/Modal/Modal.tsx
  src/pages/admin/auth/login/AdminLoginPage.tsx
  src/pages/admin/auth/register/RegisterClubPage.tsx
  src/types/modal.types.ts
Labels: 🐞 BugFix, ✨ Feature

#99 어드민 동아리 등록 로직 및 API 연동
  src/api/apiRequest.ts
  src/hooks/useAdminLogin.ts
  src/pages/admin/auth/register/RegisterClubPage.tsx
  src/pages/admin/union/notice/AdminNoticePage.tsx
  src/types/club-register.types.ts
  src/types/index.ts
  src/types/input_value.ts
  src/utils/imageHandler.ts
Labels: ✨ Feature

#103 동아리 어드민 상세 모집안내 API 연동
  src/constants/club-detail-register.ts
  src/hooks/useBulletPointConverter.ts
  src/pages/admin/club/detail/RecruitNotice.tsx
  src/routes/Routes.tsx
  src/types/input-value.types.ts
Labels: ✨ Feature

#105 어드민 로그인 / 로그아웃 플로우 개선
  index.html
  src/components/Common/HeaderMenu.tsx
  src/components/Common/RootLayout.tsx
  src/constants/navigations.ts
  src/hooks/index.ts
  src/hooks/useAdminLogin.ts
  src/hooks/useAuthenticationToggle.ts
  src/hooks/usefilteredHeaderMenuList.ts
  src/index.css
  src/store/authState.ts
Labels: 🔨 Refactor

#90 동아리 상세보기 작성 과정에서 미리보기 화면 API 연동, 에러 헨들링 추가
  src/api/apiRequest.ts
  src/api/axiosInstance.ts
  src/constants/errorMessage.ts
  src/contexts/ClubDetailContext.tsx
  src/pages/club-detail-preview/ClubDetailPreview.tsx
  src/pages/club-detail/ActivityLogModal.tsx
  src/pages/club-detail/ClubDetailPage.tsx
  src/pages/club-detail/TabContents.tsx
  src/pages/club-detail/tab/Intro.tsx
  src/pages/club-detail/tab/Log.tsx
  src/pages/club-detail/tab/Recruit.tsx
  src/routes/Routes.tsx
  src/types/api.types.ts
  src/utils/getErrorMessage.ts
Labels: ✨ Feature
