Repository ERICA-Club-Hub/Frontend, pull requests merged in 2025-03, with the labels that each got.

#107 동아리 상세 각종 기능 구현
  src/components/AdminClubDetail/ClubIntro/ClubDescription.tsx
  src/components/AdminClubDetail/ClubIntro/EventSchedule.tsx
  src/components/AdminClubDetail/ClubIntro/MonthlyEventSchedule.tsx
  src/components/AdminClubDetail/SummaryInfo/RecruitmentStatus.tsx
  src/components/AdminClubDetail/index.ts
  src/config/queryClient.ts
  src/config/theme.ts
  src/constants/club-detail-register.ts
  src/constants/navigations.ts
  src/contexts/ClubIntroContext.tsx
  src/hooks/queries/useAdminClubMutation.ts
  src/hooks/queries/useAdminClubQueries.ts
  src/hooks/useAdminLogin.ts
  src/hooks/useClubIntroContext.ts
  src/hooks/usefilteredHeaderMenuList.ts
  src/main.tsx
  src/pages/admin/auth/register/RegisterClubPage.tsx
  src/pages/admin/club/detail/AdminClubDetailPage.tsx
  src/pages/admin/club/detail/ClubIntro.tsx
  src/pages/admin/club/detail/section/ClubIntroPage.tsx
  src/pages/admin/club/detail/section/RecruitNoticePage.tsx
  src/pages/admin/club/detail/section/SummaryInfoPage.tsx
  src/pages/admin/club/main/AdminClubPage.tsx
  src/pages/admin/union/notice/AdminNoticePage.tsx
  src/pages/index.ts
  src/routes/ClubAdminGurad.tsx
  src/routes/RedirectIfAuthenticated.tsx
  src/routes/Routes.tsx
  src/types/club-detail.types.ts
  src/types/club-register.types.ts
  src/types/index.ts
  src/types/input-value.types.ts
  src/types/queries.types.ts
  src/utils/imageHandler.ts
Labels: ✨ Feature, 🔨 Refactor

#109 동아리 등록 정보 수정 API 연동
  src/components/AdminClubDetail/ClubIntro/ClubDescription.tsx
  src/components/AdminClubDetail/ClubIntro/EventSchedule.tsx
  src/components/AdminClubDetail/ClubIntro/MonthlyEventSchedule.tsx
  src/components/AdminClubDetail/SummaryInfo/RecruitmentStatus.tsx
  src/components/ClubRegister/ClubCategorySelection.tsx
  src/components/ClubRegister/ClubImageUpload.tsx
  src/components/ClubRegister/ClubRegisterForm.tsx
  src/components/ClubRegister/index.ts
  src/components/Common/Dropdown/Dropdown.tsx
  src/components/Common/HeaderMenu.tsx
  src/components/Common/RootLayout.tsx
  src/hooks/actions/useBulletPointConverter.ts
  src/hooks/actions/useClickOutside.ts
  src/hooks/actions/useToggle.ts
  src/hooks/auth/useAdminLogin.ts
  src/hooks/auth/useAuthToggle.ts
  src/hooks/auth/useEditMode.ts
  src/hooks/contexts/useClubIntroContext.ts
  src/hooks/queries/useAdminClubMutation.ts
  src/hooks/queries/useAdminClubQueries.ts
  src/pages/admin/auth/login/AdminLoginPage.tsx
  src/pages/admin/auth/register/ClubRegisterPage.tsx
  src/pages/admin/auth/register/EditClubRegisterPage.tsx
  src/pages/admin/auth/register/ModifyClubRegisterPage.tsx
  src/pages/admin/auth/register/RegisterClubPage.tsx
  src/pages/admin/club/detail/section/RecruitNoticePage.tsx
  src/pages/admin/club/detail/section/SummaryInfoPage.tsx
  src/pages/admin/club/main/AdminClubPage.tsx
  src/pages/club-detail/ActivityLogModal.tsx
  src/pages/index.ts
  src/routes/Routes.tsx
  src/styles/admin-club-register.ts
  src/types/input-value.types.ts
  src/utils/convertImageToFile.ts
  src/utils/filterHeaderMenus.ts
  src/utils/index.ts
  src/utils/uploadImageWithPreview.ts
Labels: ✨ Feature, 🔨 Refactor

#110 총동연 공지사항 API 연동
  src/api/auth/reissue.ts
  src/components/AdminClubDetail/ClubIntro/ClubDescription.tsx
  src/components/AdminClubDetail/ClubIntro/MonthlyEventSchedule.tsx
  src/components/ClubRegister/ClubRegisterForm.tsx
  src/components/Common/Button.tsx
  src/components/Common/Card.tsx
  src/components/Common/Modal/ActionModal.tsx
  src/components/Common/Modal/Modal.tsx
  src/components/UnionNotice/ThumbnailImageUpload.tsx
  src/components/UnionNotice/UnionNoticeList.tsx
  src/components/UnionNotice/UnionNoticeRegisterForm.tsx
  src/components/UnionNotice/index.ts
  src/hooks/auth/useAdminLogin.ts
  src/hooks/auth/useAuthToggle.ts
  src/hooks/auth/useEditMode.ts
  src/hooks/queries/useAdminClubMutation.ts
  src/hooks/queries/useAdminClubQueries.ts
  src/hooks/queries/useClubRegisterQueries.ts
  src/hooks/queries/useUnionQueries.ts
  src/pages/admin/club/detail/section/ClubIntroPage.tsx
  src/pages/admin/club/detail/section/RecruitNoticePage.tsx
  src/pages/admin/club/detail/section/SummaryInfoPage.tsx
  src/pages/admin/club/main/AdminClubPage.tsx
  src/pages/admin/union/notice/AdminNoticePage.tsx
  src/pages/admin/union/notice/AdminUnionNoticeEditPage.tsx
  src/pages/admin/union/notice/AdminUnionNoticePage.tsx
  src/pages/admin/union/notice/AdminUnionNoticeRegisterPage.tsx
  src/pages/index.ts
  src/pages/notice/UnionNoticePage.tsx
  src/routes/RedirectIfAuthenticated.tsx
  src/routes/Routes.tsx
  src/store/clubIdState.ts
  src/store/clubInfoState.ts
  src/types/input-value.types.ts
  src/types/modal.types.ts
  src/utils/filterHeaderMenus.ts
Labels: ✨ Feature, 🔨 Refactor

#119 feat: 자료실 다운로드 로직 구현 (#117)
  src/pages/resources/ResourcesPage.tsx
Labels: ✨ Feature

#120 feat: 자료실 다운로드 로직 구현 (#117)
  src/pages/resources/ResourcesPage.tsx
Labels: ✨ Feature

#133 feat: 메인페이지 배너/ 설문조사 UI 및 로직 구현 (#131)
  src/assets/common/MainThumbnail.svg
  src/assets/common/surveyBox.svg
  src/assets/common/surveyCard_arrow.svg
  src/pages/club-list/ClubListPage.tsx
Labels: ✨ Feature

#137 서비스 어드민 동아리 등록 요청 관리 페이지 및 기능
  src/components/AdminClubDetail/ClubIntro/ClubDescription.tsx
  src/components/AdminClubDetail/ClubIntro/MonthlyEventSchedule.tsx
  src/constants/navigations.ts
  src/hooks/queries/useClubAdminQueries.ts
  src/hooks/queries/useServiceAdminQueries.ts
  src/pages/admin/club/detail/section/ClubIntroPage.tsx
  src/pages/admin/club/detail/section/RecruitNoticePage.tsx
  src/pages/admin/club/detail/section/SummaryInfoPage.tsx
  src/pages/admin/service/AdminClubRegisterManagePage.tsx
  src/pages/index.ts
  src/routes/Routes.tsx
  src/routes/ServiceAdminGuard.tsx
Labels: ✨ Feature

#139 3차 merge [develop -> main]
  src/hooks/queries/useClubAdminQueries.ts
  src/pages/FAQ/FAQPage.tsx
Labels: :earth_asia: Deploy

#130 자료실 업로드 헤더 이슈 해결, Toast 메세지 공통 컴포넌트 제작
  src/assets/common/hanjari-logo.svg
  src/assets/common/warnIcon.svg
  src/components/ClubDetail/ActivityLogModal.tsx
  src/components/Common/Toast.tsx
  src/constants/DEFAULT_IMG.ts
  src/hooks/actions/useToast.ts
  src/main.tsx
  src/pages/admin/union/resources/AdminResourcesRegisterPage.tsx
  src/pages/club-detail/ClubDetailPage.tsx
  src/pages/club-detail/tab/Intro.tsx
  src/store/toast.ts
  src/utils/getDefaultImg.ts
Labels: 🐞 BugFix, ✨ Feature

#140 스플래시 구현
  src/App.tsx
  src/assets/splash/logo-text.svg
  src/assets/splash/logo.svg
  src/components/ClubRegister/ClubRegisterForm.tsx
  src/components/Common/RootLayout.tsx
  src/components/Common/Toast.tsx
  src/constants/DEFAULT_IMG.ts
  src/hooks/actions/useSplash.ts
  src/hooks/queries/useClubRegisterQueries.ts
  src/pages/admin/club/detail/section/ClubIntroPage.tsx
  src/pages/admin/club/detail/section/RecruitNoticePage.tsx
  src/pages/admin/club/detail/section/SummaryInfoPage.tsx
  src/pages/club-detail/ClubDetailPage.tsx
  src/pages/club-list/ClubListPage.tsx
  src/pages/index.ts
  src/pages/splash/SplashScreen.tsx
  src/routes/Routes.tsx
Labels: ✨ Feature

#141 4차 merge [develop -> main]
  index.html
  src/App.tsx
  src/assets/common/hanjari-logo.svg
  src/assets/common/warnIcon.svg
  src/assets/splash/logo-text.svg
  src/assets/splash/logo.svg
  src/components/ClubDetail/ActivityLogModal.tsx
  src/components/ClubRegister/ClubRegisterForm.tsx
  src/components/Common/RootLayout.tsx
  src/components/Common/Toast.tsx
  src/constants/DEFAULT_IMG.ts
  src/hooks/actions/useSplash.ts
  src/hooks/actions/useToast.ts
  src/hooks/queries/useClubRegisterQueries.ts
  src/main.tsx
  src/pages/admin/club/detail/section/ClubIntroPage.tsx
  src/pages/admin/club/detail/section/RecruitNoticePage.tsx
  src/pages/admin/club/detail/section/SummaryInfoPage.tsx
  src/pages/admin/union/resources/AdminResourcesRegisterPage.tsx
  src/pages/club-detail/ClubDetailPage.tsx
  src/pages/club-detail/tab/Intro.tsx
  src/pages/club-list/ClubListPage.tsx
  src/pages/index.ts
  src/pages/splash/SplashScreen.tsx
  src/routes/Routes.tsx
  src/store/toast.ts
  src/utils/getDefaultImg.ts
Labels: :earth_asia: Deploy

#146 bugfix: 메인페이지 동아리 검색 개수 제한문제 해결 (#145)
  src/pages/club-list/ClubListPage.tsx
Labels: 🐞 BugFix

#149 배포 요청사항 반영
  index.html
  public/maskable-icon-512x512.png
  public/thumbnail.png
  src/components/ActivityLog/ActivityLogForm.tsx
  src/components/ActivityLog/Feed.tsx
  src/components/ActivityLog/index.ts
  src/components/AdminClubDetail/ClubIntro/ClubDescription.tsx
  src/components/AdminClubDetail/ClubIntro/MonthlyEventSchedule.tsx
  src/components/ClubRegister/ClubImageUpload.tsx
  src/components/ClubRegister/ClubRegisterForm.tsx
  src/components/Common/Card.tsx
  src/components/Common/ImageUpload.tsx
  src/components/UnionNotice/UnionNoticeRegisterForm.tsx
  src/components/UnionNotice/index.ts
  src/hooks/queries/useClubAdminQueries.ts
  src/hooks/queries/useClubRegisterQueries.ts
  src/hooks/queries/useUnionQueries.ts
  src/pages/FAQ/FAQPage.tsx
  src/pages/admin/auth/register/CompleteClubRegisterPage.tsx
  src/pages/admin/club/activity/AdminActivitiesFeedPage.tsx
  src/pages/admin/club/activity/AdminActivityLogPage.tsx
  src/pages/admin/club/activity/EditAdminActivityLogPage.tsx
  src/pages/admin/club/activity/RegisterAdminActivityLogPage.tsx
  src/pages/admin/club/detail/section/ClubIntroPage.tsx
  src/pages/admin/club/detail/section/RecruitNoticePage.tsx
  src/pages/admin/club/detail/section/SummaryInfoPage.tsx
  src/pages/admin/club/main/AdminClubPage.tsx
  src/pages/index.ts
  src/routes/Routes.tsx
  src/styles/button.ts
  src/types/club-detail.types.ts
  src/types/input-value.types.ts
  src/utils/convertImageToFile.ts
  src/utils/dateFormatHandler.ts
  src/utils/setDefaultImg.ts
  src/utils/uploadImageWithPreview.ts
Labels: 🐞 BugFix, 🔨 Refactor

#150 동아리 등록 정보 기본 이미지 설정 제거
  src/components/ClubRegister/ClubRegisterForm.tsx
  src/hooks/queries/useClubRegisterQueries.ts
  src/pages/admin/club/main/AdminClubPage.tsx
Labels: 🐞 BugFix

#153 동아리 상세 월별 일정 입력 오류 수정 및 삭제 기능 구현
  src/components/AdminClubDetail/ClubIntro/EventSchedule.tsx
  src/hooks/queries/useClubAdminQueries.ts
  src/pages/admin/club/detail/section/ClubIntroPage.tsx
Labels: ✨ Feature, 🔥 Hotfix

#154 6차 merge [develop -> main]
  src/components/AdminClubDetail/ClubIntro/EventSchedule.tsx
  src/hooks/queries/useClubAdminQueries.ts
  src/pages/admin/club/detail/section/ClubIntroPage.tsx
Labels: :earth_asia: Deploy, 🔥 Hotfix

#159 동아리 등록 시 나타나는 에러가 사진 용량 때문일 때 toast 메세지 띄우기 및 동아리 상세 페이지 각종 버그 수정
  src/api/axiosInstance.ts
  src/constants/MAX_FILE_SIZE.ts
  src/hooks/queries/useClubRegisterQueries.ts
  src/pages/club-detail/ClubDetailPage.tsx
  src/pages/club-detail/tab/Log.tsx
  src/pages/club-detail/tab/Recruit.tsx
  src/utils/calculateFileSize.ts
  src/utils/isValidUrl.ts
Labels: ✨ Feature

#162 동아리 정보 문구 수정 및 월별 일정 삭제 로직 변경
  src/components/AdminClubDetail/ClubIntro/EventSchedule.tsx
  src/constants/club-detail-register.ts
  src/hooks/queries/useClubAdminQueries.ts
  src/pages/admin/club/detail/section/ClubIntroPage.tsx
  src/pages/admin/club/detail/section/SummaryInfoPage.tsx
  src/types/club-detail.types.ts
Labels: 🔥 Hotfix

#163 7차 merge [develop -> main]
  src/api/axiosInstance.ts
  src/components/AdminClubDetail/ClubIntro/EventSchedule.tsx
  src/constants/MAX_FILE_SIZE.ts
  src/constants/club-detail-register.ts
  src/hooks/queries/useClubAdminQueries.ts
  src/hooks/queries/useClubRegisterQueries.ts
  src/pages/admin/club/detail/section/ClubIntroPage.tsx
  src/pages/admin/club/detail/section/SummaryInfoPage.tsx
  src/pages/club-detail/ClubDetailPage.tsx
  src/pages/club-detail/tab/Log.tsx
  src/pages/club-detail/tab/Recruit.tsx
  src/types/club-detail.types.ts
  src/utils/calculateFileSize.ts
  src/utils/isValidUrl.ts
Labels: :earth_asia: Deploy

#164 feat: 메인페이지 수정사항 (#161)
  src/assets/common/MainThumbnail.svg
  src/assets/common/whoMake.svg
  src/components/Common/Modal/Modal.tsx
  src/pages/FAQ/FAQPage.tsx
  src/pages/club-list/ClubListPage.tsx
  src/pages/notice/ServiceNoticePage.tsx
  src/types/modal.types.ts
Labels: ✨ Feature

#166 hotfix: 공통 컴포넌트 모달 오류 해결 (#165)
  src/components/Common/Footer.tsx
  src/components/Common/Modal/MainModal.tsx
  src/components/Common/Modal/Modal.tsx
  src/pages/club-list/ClubListPage.tsx
Labels: 🔥 Hotfix

#170 8차 merge [develop -> main]
  index.html
  src/assets/common/MainThumbnail.svg
  src/assets/common/whoMake.svg
  src/components/Common/Footer.tsx
  src/components/Common/Modal/FeedbackModal.tsx
  src/pages/FAQ/FAQPage.tsx
  src/pages/club-list/ClubListPage.tsx
  src/pages/notice/ServiceNoticePage.tsx
  src/types/modal.types.ts
Labels: :earth_asia: Deploy

#171 동아리 상제 정보 요약 UI 수정 [develop -> main]
  src/pages/club-detail/ClubDetailPage.tsx
Labels: :earth_asia: Deploy, 🔥 Hotfix

#175 로고 홈 라우팅 추가
  src/components/Common/HeaderMenu.tsx
Labels: :earth_asia: Deploy

#177 fix : 연간 일정 flex 부여 및 정렬 기준 수정
  src/pages/club-detail/tab/Intro.tsx
Labels: 🐞 BugFix

#179 활동로그 수정 API 로직 구현
  src/components/ActivityLog/ActivityLogForm.tsx
  src/components/ActivityLog/CarouselImage.tsx
  src/components/Common/ImageUpload/ImageListUpload.tsx
  src/components/Common/Toast.tsx
  src/hooks/handler/useErrorHandler.ts
  src/hooks/queries/useClubAdminQueries.ts
  src/hooks/queries/useClubRegisterQueries.ts
  src/hooks/queries/useServiceAdminQueries.ts
  src/hooks/queries/useUnionQueries.ts
  src/pages/admin/club/main/AdminClubPage.tsx
  src/types/activity-log.types.ts
  src/utils/convertImageToFile.ts
  src/utils/convertURLtoFile.ts
Labels: ✨ Feature

#182 로딩 공통 컴포넌트 및 Pending 핸들러 로직 구현
  src/components/ActivityLog/ActivityLogForm.tsx
  src/components/ActivityLog/Feed.tsx
  src/components/ClubRegister/ClubRegisterForm.tsx
  src/components/Common/Loading/LoadingModal.tsx
  src/components/Common/Loading/Skeleton.tsx
  src/components/Common/Modal/Modal.tsx
  src/hooks/queries/useClubAdminQueries.ts
  src/pages/admin/club/activity/AdminActivitiesFeedPage.tsx
  src/pages/admin/club/detail/section/ClubIntroPage.tsx
  src/pages/admin/club/detail/section/RecruitNoticePage.tsx
  src/pages/admin/club/detail/section/SummaryInfoPage.tsx
  src/types/modal.types.ts
Labels: 🐞 BugFix, ✨ Feature, 🔨 Refactor

#183 로딩 공통 컴포넌트 및 Pending 핸들러 로직 구현 [develop -> main]
  src/components/ActivityLog/ActivityLogForm.tsx
  src/components/ActivityLog/Feed.tsx
  src/components/ClubRegister/ClubRegisterForm.tsx
  src/components/Common/Loading/LoadingModal.tsx
  src/components/Common/Loading/Skeleton.tsx
  src/components/Common/Modal/Modal.tsx
  src/hooks/queries/useClubAdminQueries.ts
  src/pages/admin/club/activity/AdminActivitiesFeedPage.tsx
  src/pages/admin/club/detail/section/ClubIntroPage.tsx
  src/pages/admin/club/detail/section/RecruitNoticePage.tsx
  src/pages/admin/club/detail/section/SummaryInfoPage.tsx
  src/types/modal.types.ts
Labels: :earth_asia: Deploy

#186 활동로그 상세, 어드민 동아리 소개 토큰 만료 임시 에러 핸들링
  src/api/apiRequest.ts
  src/components/ActivityLog/ActivityLogForm.tsx
  src/components/AdminClubDetail/ClubIntro/MonthlyEventSchedule.tsx
  src/hooks/queries/useClubAdminQueries.ts
Labels: :earth_asia: Deploy, 🔥 Hotfix

#188 활동로그, 월별 일정 세션 만료 에러 핸들링
  src/components/ActivityLog/ActivityLogForm.tsx
  src/components/AdminClubDetail/ClubIntro/MonthlyEventSchedule.tsx
  src/hooks/queries/useClubAdminQueries.ts
Labels: :earth_asia: Deploy, 🔥 Hotfix
