Repository ERICA-Club-Hub/Frontend, pull requests merged in 2025-01, with the labels that each got.

#16 개발 환경 세팅
  src/App.tsx
  src/assets/common/error-icon.svg
  src/main.tsx
  src/pages/error/ErrorPage.tsx
  src/pages/index.ts
Labels: ✨ Feature

#17 [Feat] TOP NAVI 공통 컴포넌트 UI 구현
  .prettierrc
  src/components/Common/TopNavigator.tsx
  src/components/Common/index.ts
  src/constants/navigations.ts
  src/pages/admin/auth/login/AdminLoginPage.tsx
Labels: ✨ Feature

#18 [Refactor] TOP NAVI 컴포넌트 활성화 상태 전역 상태로 관리
  src/components/Common/TopNavigator.tsx
  src/pages/admin/auth/login/AdminLoginPage.tsx
  src/store/navAtom.ts
Labels: 🔨 Refactor

#19 feat : Button 공통 컴포넌트 구현 및 호출
  src/components/Common/Button.tsx
  src/components/Common/RootLayout.tsx
  yarn.lock
Labels: ✨ Feature

#21 [Refactor] TOP NAVI 컴포넌트 활성화 로컬 상태로 관리
  src/components/Common/TopNavigator.tsx
  src/pages/admin/auth/login/AdminLoginPage.tsx
  src/store/navAtom.ts
Labels: 🔨 Refactor

#22 8 admin login UI
  src/components/Common/Input.tsx
  src/components/Common/index.ts
  src/pages/admin/auth/login/AdminLoginPage.tsx
Labels: ✨ Feature

#23 feat: 동아리 어드민 홈 UI 구현
  src/assets/common/home-icon.svg
  src/components/Common/ArrowLinkButton.tsx
  src/components/Common/HeaderMenu.tsx
  src/components/Common/Input.tsx
  src/components/Common/RootLayout.tsx
  src/components/Common/index.ts
  src/pages/admin/auth/login/AdminLoginPage.tsx
  src/pages/admin/club/main/AdminClubPage.tsx
Labels: ✨ Feature, 🔨 Refactor

#25 feat: 총동연 어드민 홈 UI 구현
  src/pages/admin/union/main/AdminUnionPage.tsx
Labels: ✨ Feature

#44 feat: 어드민 등록 UI 구현
  src/assets/common/expand-arrow.svg
  src/components/Common/Dropdown.tsx
  src/components/Common/HeaderMenu.tsx
  src/components/Common/InputField.tsx
  src/components/Common/RootLayout.tsx
  src/components/Common/index.ts
  src/pages/admin/auth/login/AdminLoginPage.tsx
  src/pages/admin/auth/register/RegisterClubPage.tsx
Labels: ✨ Feature

#48 feat: 총동연 공지사항 등록 UI
  src/pages/admin/auth/register/RegisterClubPage.tsx
  src/pages/admin/union/notice/AdminNoticePage.tsx
  src/types/index.ts
  src/types/input_value.ts
  src/utils/imageHandler.ts
  src/utils/index.ts
Labels: ✨ Feature

#50 45 club detail UI
  src/assets/common/card.svg
  src/assets/common/jjang.svg
  src/assets/common/label.svg
  src/assets/common/logo.svg
  src/assets/common/phone.svg
  src/assets/common/sns.svg
  src/pages/club-detail/ClubDetailPage.tsx
  src/pages/club-detail/TabContents.tsx
  src/pages/club-detail/tab/Intro.tsx
  src/pages/club-detail/tab/Log.tsx
  src/pages/club-detail/tab/Recruit.tsx
  yarn.lock
Labels: ✨ Feature

#56 feat: 컴파운드 패턴을 활용한 Dropdown 컴포넌트 분리 및 로직 구조화
  src/components/Common/Dropdown.tsx
  src/components/Common/Dropdown/Dropdown.tsx
  src/components/Common/Dropdown/Header.tsx
  src/components/Common/Dropdown/Menu.tsx
  src/components/Common/Dropdown/index.ts
  src/components/Common/index.ts
  src/constants/navigations.ts
  src/hooks/useClickOutside.ts
  src/hooks/useToggle.ts
  src/pages/admin/auth/register/RegisterClubPage.tsx
  src/pages/admin/club/activity/AdminActivityLogPage.tsx
Labels: 🔨 Refactor

#64 46 activity log modal UI
  src/hooks/useClickOutside.ts
  src/pages/club-detail/ActivityLogModal.tsx
  src/pages/club-detail/tab/Log.tsx
Labels: ✨ Feature
